### ISSUE TITLE
The video needs to be cut into two

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/ruby-methods-readme#11]
The second half of the video is about method arguments, which should be part of the next readme (Methods and Arguments)

**Comment by aviflombaum** [comment]
agreed. we should do this eventually.

**Comment by AnnJohn** [comment]
Removed the video from this lesson for now.

**Comment by dfenjves** [comment]
Why are we removing the video?

**Comment by AnnJohn** [comment]
Other issues raised on this lesson were about the video so @jmburges wanted to remove it. 

Also, the video covers a lot of material that this readme, textwise, does not. I can though revert this commit, and then make a new repo for one without it.

**Comment by jmburges** [comment]
Should re remove, or make a new repo with it removed to make sure it doesn’t mess up anyone elses track?


On October 28, 2015 at 12:07:10 PM, AnnJohn (notifications@github.com) wrote:

Other issues raised on this lesson were about the video so @jmburges wanted to remove it.

Also, the video covers a lot of material that this readme, textwise, does not. I can though revert this commit, and then make a new repo for one without it.
