### ISSUE TITLE
Coding Challenge shouldn't care about comments

### ISSUE THREAD

**Issue by wifelette** [learn-co-curriculum/ruby-methods-readme#12]
Or, if it *does*, the instructions should explicitly tell me to delete the comments :p My submission failed, but my code was fine—I just needed to have deleted the comments.

**Comment by SophieDeBenedetto** [comment]
Hi @wifelette, the coding challenge in the browser (which I think is what you are referring to) doesn't care about comments per se. It's that the last line that you type into that input box needs to be the invocation of the method. We will make that more clear, but the existence of comments (_not on the last line_) does not matter. 

Thanks for your input!
