### ISSUE TITLE
"You do not have access to this lesson." error message

### ISSUE THREAD

**Issue by aliciayu** [learn-co-curriculum/ruby-methods-readme#25]
Hello, I am not sure why I am getting this red banner error message. I am following the flow of the lessons and I wanted to open "Learn" to practice what I have just learned but "Open" is not available.

Is there any way that I can fix this or know what I am doing incorrectly?

Thank you

**Comment by Joll59** [comment]
@aliciayu Sorry for the delayed response If this issue persists.
Please ask a question using Slack or the ask a question feature on Learn.co.

Thank you.
