### ISSUE TITLE
Lesson written as if there is an IDE?

### ISSUE THREAD

**Issue by s-blais** [learn-co-curriculum/ruby-methods-readme#26]
Hi, unless I'm missing something, this lesson includes instructions that imply the IDE is available to open and use (the "open IDE" button isn't there for this lesson, however, see attached screenshot:)

![Screen Shot 2019-06-26 at 12 00 22 PM](https://user-images.githubusercontent.com/51341914/60196081-5f735680-980a-11e9-8c8d-c8023d554943.png)

"Try it out. Make a new file called greeting.rb (you can use: touch greeting.rb from your terminal). Put the following code in it:..."

I then thought, ah, it is instructing me to use the Terminal app irb, but irb doesn't create files or recognize "touch" ....  

I was able to approximate the lesson closely enough in repl.it, however, without the creating-file part of it. 

Not sure if there's a hiccup of the IDE button not displaying, or if the lesson text itself is confusing (perhaps only to me?). Thanks!

**Comment by maxwellbenton** [comment]
Hi @s-blais,

Thank you for opening this issue! We've taken a look at this lesson and made some updates based on your feedback. We've added a folder with a file to code along in that will now cause Learn to add in the Open IDE button. We've also updated the instructions to make it clearer that while some portions of this lesson can be followed along in IRB, the file creation part at the end must be done in the terminal using bash commands, which should prevent this confusion in the future.

Thank you for contributing to this lesson!
