### ISSUE TITLE
Lesson Marked Incomplete After Completing

### ISSUE THREAD

**Issue by Andrew-J-Williams** [learn-co-curriculum/ruby-methods-readme#28]
I finished the lab and completed the reading, moving on to the next lesson, but in my drop-down menu and my lessons tab, it still shows 'Intro to Methods' as incomplete.

I'm not sure if I did something wrong or it's just a glitch, looking for some help on this one!
<img width="1440" alt="Screen Shot 2019-08-18 at 2 49 04 PM" src="https://user-images.githubusercontent.com/52223544/63229920-39937e00-c1cb-11e9-9649-4b9c22e2273c.png">

**Comment by AnthonyM530** [comment]
I'm having the same issue where the lab is completed but is counted as an incomplete lesson

**Comment by jo-hooton** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

In fact, there's a great article about this very issue over in the [Learn Help Center](https://help.learn.co/en/articles/493053-lights-not-turning-green). Check it out! 🎉

If you still require assistance after reading the Help Center article, pop into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
