### ISSUE TITLE
Not appearing green check marks after completed the lab

### ISSUE THREAD

**Issue by lisaluvkode** [learn-co-curriculum/ruby-methods-readme#35]
Hi! I completed the lab. But it mark as yellow circle beside this lesson. Please let me know what happen?

**Comment by MinimumViablePerson** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
